### PR TITLE
Hashspeed * 9

### PR DESCRIPTION
**Pull request by robvanmieghem**

### CODE REVIEW

**Comment by DavidVorick** [comment]
I can't tell you how glad I am to see this. Thanks.

Testing it now.

**Comment by DavidVorick** [comment]
At the very least, it doesn't hurt the speeds on the nvidia cards.

I'm going to take your word for it that it does good things for AMD cards.

**Comment by robvanmieghem** [comment]
it increased the speed on my AMD HD 7970 from 75 MH/s to 650 MH/s

**Comment by DavidVorick** [comment]
0.0

I hope everyone else sees similar improvements. Thanks again.

**Pull request merged**
